swagger: '2.0'
info:
  description: Набор сервисов для работы с системой учета /ООО Ромашка/
  version: "1.0.0"
  title: RestAPI
consumes:
  - application/json
  - application/xml
  - application/text
produces:
  - application/json  
  - application/xml
  - application/text  
basePath: "/api"   

paths:
  /reports/formats:
    get:
      summary: Получить список форматов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере    
        default:
          description: Неизвестная ошибка      
           
  /reports/entities:
    get:
      summary: Получить список типов данных
      operationId: main.entities
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере    
        default:
          description: Неизвестная ошибка     

  /reports/{entity}/{format}:
    get:
      summary: Получить данные
      operationId: main.get_report
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере    
        default:
          description: Неизвестная ошибка   
    parameters:
    - name: entity
      in: path
      description: Уникальное наименование типа данных (/reports/entities)
      required: true
      type: string
    - name: format
      in: path
      description: Уникальный код формата (/reports/formats)
      required: true
      type: integer



   
           
                  

                  


 